42 - Form: Starting point
WeAreSnook/connected-camden pull request #86
Opened 2020-11-11 17:40 UTC by francosta

Apologies @tosbourn and @mathewtrivett for the amount of commits and file changes in a single PR. As I said, this has largely to do with the need to setup several things to get started on the current issue.

Things that are included in here but are not strictly related to the issue:
- Added `rails-controller-testing` gem. This is something I should have added when setting up the testing framework;
- Added the `wicked` gem to support a multi-step form;
- Created a `Trip` model with a `starting_point` `string` attribute, with validation for `presence`;
- Added a controller for `Trip` with a single `route` for `/trips/new`. Added logic to this action to redirect to the `trip_builder` controller;
- Added validation test for `starting_point  on `Trip` model;
- Added test for `Trip` controller;

Things that are related to the issue:
- Added a controller for the TripBuilder in order to support the form with `wicked`. This controller only has a `starting_point` `:step` for now. Also included the minimum setup for the wizard to render and function;
- Installed the `js-autocomplete` npm package to support autocomplete functionality on `starting_point` input form.
- Added autocomplete logic in `javascript/components/autocomplete.js` with hardcoded options for dropdown and no call to the Google Places API;
- Added view for `starting_point`;
- Added internationalization variables for `starting_point` form and link;
- Added test for `show` on `TripBuilderController`;

I will need some help with tests. I've done the most I could but have not been able to test the view created for `starting_point` and, possibly, others. I don't think we should want to merge this before at least there are some assertions about what's in the view.

Closes #42

2020-11-11 18:01 UTC, mathewtrivett reviewed
This looks like a great start Fran. Let's pick up pairing on writing tests for the views together tomorrow.

2020-11-12 10:26 UTC, francosta commented on app/views/trip_builder/starting_point.html.erb
> +<%= link_to "#{t('back')}", "/"%>
Yes Mat - thanks. I definitely agree on the handlers and will change it. 🙌

2020-11-12 17:04 UTC, tosbourn requested changes
A few minor changes, but looking great. I love how much you've accomplished with relatively little code.

2020-11-12 17:04 UTC, tosbourn commented on app/views/trip_builder/starting_point.html.erb
> +<%= link_to "#{t('back')}", "/"%>
One small comment about this line as well.

Anytime we write `"#{something}"` and there are no other bits of the string, we can remove the need to interpolate that data by just writing `something`.

In this case:

``` diff
- <%= link_to "#{t('back')}", "/"%>
+ <%= link_to t('back'), root_path %>
```

2020-11-12 17:04 UTC, tosbourn commented on spec/test/controllers/trip_controller_spec.rb
> +      response.should redirect_to '/trip_builder'
ideally, yes, we would use a URL helper here.

The rule of thumb should be:

- If we care about the specifics of the URL for branding reasons, compare against a hardcoded string
- Any other time, use a helper

For example, if the test was "we always use the term articles for the URL, even though our system calls them posts" (terrible test name, but you get the idea) then we would care that `/articles` was hit.

2020-11-12 17:04 UTC, tosbourn commented
Also, thanks for the super clear PR description, so easy to read!

2020-11-13 09:49 UTC, merged