52 button
WeAreSnook/connected-camden pull request #96
Opened 2020-11-13 17:15 UTC by francosta

Added Button component and tests. Made content optional as indicated in the issue(?).
For passing styling, I set a style attribute to the button that will be appended to the class 'button-'. We can change this implementation. It would maybe be good to limit the options passed to style to 'positive' or 'negative', if this is the only thing we want the styles to illustrate, as per the ticket.

Closes #52

2020-11-16 09:12 UTC, francosta commented on app/components/button_component.html.erb
> +<button class=<%= "button-#{@style}" %> >
This is really good @mathewtrivett. Thanks for the detailed explanation - I didn't know about variants and they look great. 🙌 
I agree that the variant pattern is cleaner and also seems to make more sense in the 'Rails' environment. I will change it to be so.

2020-11-16 09:14 UTC, mathewtrivett commented on app/components/button_component.html.erb
> +<button class=<%= "button-#{@style}" %> >
I think have a look at it, I'm not totally clear if it is possible to initialize and object and call it like this. So experiment with it. We'll see what @tosbourn says but I feel like we want to refactor all our tests and components to use Rails view helpers as much as possible.

2020-11-16 12:54 UTC, tosbourn commented on app/components/button_component.html.erb
> +<button class=<%= "button-#{@style}" %> >
My only experience with ViewComponent is what has been done on Safety Tech, where we didn't have a need for variants (or at least, didn't use them!)

It seems like a really cool feature and the way to use it feels very railsy. Even having never seen the implementation before reading `with_varient(:primary)` made me think "oh this will be like a button but with a slight change".

More than happy to adopt this approach.

2020-11-17 12:24 UTC, mathewtrivett requested changes

2020-11-17 12:24 UTC, mathewtrivett commented on app/components/button_component.html.erb
> +<button class=<%= "button-#{@style}" %> >
@francosta instead of using the with_variant approach. Could you refactor this to use conditional rendering? With the variant approach it is not possible to initialise from what I can tell.

2020-11-17 12:44 UTC, francosta commented
Sure @mathewtrivett , will do

2020-11-17 13:45 UTC, francosta commented
@mathewtrivett I've refactored and introduced new test for styling.

2020-11-17 15:31 UTC, mathewtrivett approved these changes

2020-11-17 15:33 UTC, mathewtrivett commented
This looks good to me @francosta great work!

2020-11-17 15:33 UTC, merged